Server:
  host: 0.0.0.0
  port: 19132
  motd: "Dedicated LeafMCBE Server"
  version: 1.19.50
LeafMCBE:
  debug: true
  showDateOnLogging: true
  doNotCrashOnError: true
World:
  gamemode: "creative" # survival / creative / adventure
  dimension: "flat" # overworld / flat / nether / end / void
  biome: "plains" # https://minecraft-data.prismarine.js.org/?v=bedrock_1.19.50&d=biomes